/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "app-bg": "#F7F5F1",
        "app-surface": "#FFFFFF",
        "app-text-primary": "#171310",
        "app-text-secondary": "#514A44",
        "app-text-muted": "#81786F",
        "app-border": "#DED7CF",
        "app-border-light": "#EFEAE3",
        "app-border-sidebar": "#DDD6CE",
        "app-border-header": "#D8D1C9",
        "app-accent": "#8A5A3C",
        "app-accent-hover": "#74492E",
        "app-accent-subtle": "rgba(138, 90, 60, 0.08)",
        "app-accent-active": "#EDE6DF",
        "app-success": "#4F6B52",
        "app-success-bg": "#F1F5F2",
        "app-warning": "#9A6A32",
        "app-warning-bg": "#FAF5EE",
        "app-error": "#9A4540",
        "app-dark": "#24170F",
        "app-dark-card": "#302016",
        "app-dark-border": "#432E22",
        "app-copper": "#C59B7D",
        "app-copper-hover": "#D8AC8E",
        "primary-fixed": "#ffdbc8",
        "secondary-container": "#f4dbcd",
        "surface-bright": "#fff8f5",
        "on-surface-variant": "#51443d",
        "surface-container-high": "#f0e6e1",
        "on-tertiary-fixed-variant": "#5e4026",
        "inverse-on-surface": "#f9efe9",
        "inverse-surface": "#342f2c",
        "on-primary-fixed": "#321300",
        "on-secondary-fixed-variant": "#544339",
        secondary: "#6d5b50",
        "surface-container-low": "#fcf2ec",
        "on-primary-container": "#ffddca",
        "on-background": "#1f1b18",
        "surface-container-highest": "#eae1db",
        tertiary: "#66462c",
        "on-secondary-container": "#725f54",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#f7b995",
        background: "#fff8f5",
        "surface-container": "#f6ece6",
        "outline-variant": "#d6c3b9",
        "secondary-fixed-dim": "#dac2b5",
        primary: "#6e4327",
        "on-surface": "#1f1b18",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#eae1db",
        "surface-tint": "#825336",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "tertiary-container": "#805e42",
        "primary-container": "#8a5a3c",
        "secondary-fixed": "#f7ddd0",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdcc2",
        surface: "#fff8f5",
        "on-error": "#ffffff",
        "surface-dim": "#e2d8d3",
        "tertiary-fixed-dim": "#eabe9c",
        "on-tertiary-fixed": "#2d1602",
        "on-primary-fixed-variant": "#673c21",
        "on-secondary-fixed": "#261911",
        "inverse-primary": "#f7b995",
        "on-tertiary-container": "#ffddc4",
        "on-secondary": "#ffffff",
        outline: "#84746c"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "margin-tablet": "2.5rem",
        "margin-mobile": "1.25rem",
        "space-lg": "1.75rem",
        "space-xs": "0.25rem",
        "space-xl": "3rem",
        "margin-desktop": "5rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "2rem",
        "gutter-mobile": "1rem",
        gutter: "1.5rem",
        "space-md": "1rem",
        margin: "1.5rem"
      },
      fontFamily: {
        sans: ["Geist", "ui-sans-serif", "system-ui", "-apple-system", "sans-serif"],
        serif: ["Newsreader", "Georgia", "serif"],
        "body-lg": ["Geist"],
        "headline-sm": ["Newsreader"],
        "body-sm": ["Geist"],
        "editorial-italic": ["Newsreader"],
        "headline-md": ["Newsreader"],
        "display-hero-mobile": ["Newsreader"],
        "display-hero": ["Newsreader"],
        "label-caps": ["Geist"],
        "body-md": ["Geist"],
        "label-md": ["Geist"],
        "numeric-table": ["Geist"],
        "headline-lg": ["Newsreader"],
        "headline-lg-mobile": ["Newsreader"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "editorial-italic": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "numeric-table": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
